name: Deploy Preview to Cloudflare Pages

on:
  push:
    branches:
      - feature/*
      - develop
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: agriculture-japan

jobs:
  deploy:
    runs-on: ubuntu-24.04
    name: Deploy Preview
    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare deployment directory
        run: |
          # Create a temporary directory for deployment
          mkdir -p deploy
          # Copy all HTML files from root to deploy directory
          cp *.html deploy/ 2>/dev/null || true
          # Copy all files from public directory to deploy directory
          cp -r public/* deploy/
          # Ensure index.html exists in deploy directory
          if [ ! -f deploy/index.html ] && [ -f public/index.html ]; then
            cp public/index.html deploy/
          fi
      
      - name: Deploy to Cloudflare Pages (Preview)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy deploy --project-name=${{ env.PROJECT_NAME }}
